spring:
  application:
    name: user-service
  jackson:
    default-property-inclusion: NON_NULL
  config:
    import: optional:.env[.properties]
  datasource:
    url: ${SPRING_JDBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${SPRING_LIQUIBASE_DEFAULT-SCHEMA}
    url: ${SPRING_JDBC_URL}
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL}
  instance:
    prefer-ip-address: true


mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath:db/mybatis/mapper/*.xml
  type-aliases-package: com.gznznzjsn.userservice.domain

user-service:
  secrets:
    access-key: ${USER-SERVICE_SECRETS_ACCESS-KEY}
    refresh-key: ${USER-SERVICE_SECRETS_REFRESH-KEY}

